### PR TITLE
Create getting_started.md

### PR DESCRIPTION
**Pull request by ShobhitRathi**
top links for learning and getting started with java

### CODE REVIEW

**Comment by Faisal-Manzer** [comment]
Hey, move Java section to `README.md` > `Technologies and Languages` > `Java`

**Review by Faisal-Manzer — COMMENTED** [review]
Move this to README.md

**Comment by ShobhitRathi** [comment]
sure

**Comment by ShobhitRathi** [comment]
moved it, now you can merge.

**Pull request closed without merging**
